version: '2.1'
services:

    docker-vacuum:
        build:
            context: ./services/docker-vacuum
            dockerfile: Dockerfile.dev
        networks:
            - development
        ports:
            - ${HUMBLE_PORT:-8080}:8080
        environment:
            NODE_ENV: development
            LOG_LEVEL: ${LOG_LEVEL:-info}
        volumes:
            - /var/lib/docker/containers:/var/lib/docker/containers:ro
            - /var/run/docker.sock:/var/run/docker.sock
        working_dir: /usr/src/app
        entrypoint: [ "yarn", "start" ]
    
networks:
    development:
