version: '2.1'
services:

    docker-vacuum:
        build:
            context: ./services/docker-vacuum
            dockerfile: Dockerfile
        networks:
            - production
        ports:
            - ${HUMBLE_PORT}:8080
        environment:
            NODE_ENV: production
            LOG_LEVEL: ${LOG_LEVEL}
        volumes:
            - /var/lib/docker/containers:/var/lib/docker/containers:ro
            - /var/run/docker.sock:/var/run/docker.sock

networks:
    production:
